theme: minima
title: My Programming Notebook
author: Jacob Wu
email: jacob.wu@email.com
description: > # this means to ignore newlines until "baseurl:"
  Hello!

# social links
github_username:  jacobwu-b

show_excerpts: false # set to false to remove excerpts on the homepage
