theme : minima
title : My Programming Notebook
author: Jacob Wu
email : jacob.wu@email.com
url   : jacobwu.org
description: Hello!

# social links
github_username:  jacobwu-b

show_excerpts: false # set to false to remove excerpts on the homepage

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
