theme : minima
title : My Programming Notebook
author: Jacob Wu
email : jacob.wu@email.com
url   : jacobwu.org
description: Hello!

# social links
github_username:  jacobwu-b

show_excerpts: false # set to false to remove excerpts on the homepage
